#!/usr/bin/env bash
set -euo pipefail

# publish-localnet.sh — build + publish hero_forge to localnet, run create_displays
# (Hero + Sword + Shield + Armor Displays in one PTB), and write
# hero-frontend/src/deployment.ts with every resulting identifier.
#
# Prerequisites: sui CLI on PATH, jq, localnet running on 127.0.0.1:9000
# (use dapp/scripts/start-localnet.sh).

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DAPP_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
MOVE_DIR="${DAPP_DIR}/hero-move"
FRONTEND_SRC="${DAPP_DIR}/hero-frontend/src"

LOCALNET_RPC="http://127.0.0.1:9000"
FAUCET_URL="http://127.0.0.1:9123/gas"
REGISTRY_ID="0xd"
PKG_MODULE="hero"   # module name inside the package

# ── 1. Ensure active environment is localnet ─────────────────────────────────

ACTIVE_ENV=$(sui client active-env 2>/dev/null || true)
if [ "${ACTIVE_ENV}" != "localnet" ]; then
    echo "Switching to localnet environment..."
    sui client new-env --alias localnet --rpc "${LOCALNET_RPC}" 2>/dev/null || true
    sui client switch --env localnet
fi
echo "Active environment: $(sui client active-env)"

# ── 2. Fund the active address ───────────────────────────────────────────────

ACTIVE_ADDR=$(sui client active-address)
echo "Active address: ${ACTIVE_ADDR}"
curl -s -X POST "${FAUCET_URL}" \
    -H "Content-Type: application/json" \
    -d "{\"FixedAmountRequest\":{\"recipient\":\"${ACTIVE_ADDR}\"}}" \
    | jq -r '.transferredGasObjects[0].id // "faucet responded (check balance)"'

# ── 3. Build + ephemeral publish ─────────────────────────────────────────────
# See dapp/scripts/publish.sh for why test-publish + --build-env testnet.

PUBFILE="${MOVE_DIR}/.localnet-publication.json"
rm -f "${PUBFILE}"
echo "Publishing hero_forge to localnet (ephemeral test-publish)..."
PUBLISH_OUTPUT=$(sui client test-publish "${MOVE_DIR}" \
    --build-env testnet \
    --pubfile-path "${PUBFILE}" \
    --gas-budget 200000000 \
    --json)

PACKAGE_ID=$(echo "${PUBLISH_OUTPUT}" \
    | jq -r '.objectChanges[] | select(.type == "published") | .packageId')
PUBLISHER_ID=$(echo "${PUBLISH_OUTPUT}" \
    | jq -r '.objectChanges[] | select(.type == "created" and (.objectType | test("0x2::package::Publisher"))) | .objectId')

echo "Package ID:   ${PACKAGE_ID}"
echo "Publisher ID: ${PUBLISHER_ID}"

# ── 4. create_displays (Hero + 3 item Displays, one PTB) ─────────────────────

echo "Running create_displays..."
CREATE_OUTPUT=$(sui client ptb \
    --move-call "${PACKAGE_ID}::${PKG_MODULE}::create_displays" \
        "@${REGISTRY_ID}" \
        "@${PUBLISHER_ID}" \
    --gas-budget 100000000 \
    --json)

# Extract each Display<T> / DisplayCap<T> by its type parameter. Anchor "Display<"
# so it doesn't also match the DisplayCap objectType.
display_id_for() {  # $1 = type name (Hero/Sword/Shield/Armor)
    echo "${CREATE_OUTPUT}" | jq -r \
        --arg t "$1" \
        '.objectChanges[] | select(.type=="created" and (.objectType | test("display_registry::Display<.*::hero::" + $t + ">"))) | .objectId'
}
cap_id_for() {
    echo "${CREATE_OUTPUT}" | jq -r \
        --arg t "$1" \
        '.objectChanges[] | select(.type=="created" and (.objectType | test("display_registry::DisplayCap<.*::hero::" + $t + ">"))) | .objectId'
}

HERO_DISPLAY_ID=$(display_id_for Hero)
HERO_CAP_ID=$(cap_id_for Hero)
SWORD_DISPLAY_ID=$(display_id_for Sword)
SWORD_CAP_ID=$(cap_id_for Sword)
SHIELD_DISPLAY_ID=$(display_id_for Shield)
SHIELD_CAP_ID=$(cap_id_for Shield)
ARMOR_DISPLAY_ID=$(display_id_for Armor)
ARMOR_CAP_ID=$(cap_id_for Armor)

echo "Hero Display:   ${HERO_DISPLAY_ID}"
echo "Sword Display:  ${SWORD_DISPLAY_ID}"
echo "Shield Display: ${SHIELD_DISPLAY_ID}"
echo "Armor Display:  ${ARMOR_DISPLAY_ID}"

# ── 5. Write deployment.ts ───────────────────────────────────────────────────

mkdir -p "${FRONTEND_SRC}"
cat > "${FRONTEND_SRC}/deployment.ts" <<EOF
// Auto-generated by hero-scripts/publish-localnet.sh — do not edit by hand.
export const NETWORK = "localnet";
export const PACKAGE_ID = "${PACKAGE_ID}";
export const PUBLISHER_ID = "${PUBLISHER_ID}";
export const REGISTRY_ID = "${REGISTRY_ID}";

export const DISPLAYS = {
  hero:   { display: "${HERO_DISPLAY_ID}",   cap: "${HERO_CAP_ID}" },
  sword:  { display: "${SWORD_DISPLAY_ID}",  cap: "${SWORD_CAP_ID}" },
  shield: { display: "${SHIELD_DISPLAY_ID}", cap: "${SHIELD_CAP_ID}" },
  armor:  { display: "${ARMOR_DISPLAY_ID}",  cap: "${ARMOR_CAP_ID}" },
} as const;
EOF

echo ""
echo "deployment.ts written to ${FRONTEND_SRC}/deployment.ts"
echo "Done."
