#!/usr/bin/env bash
set -euo pipefail

# publish-devnet.sh — build + publish hero_forge to devnet, run create_displays
# (Hero + Sword + Shield + Armor Displays in one PTB), and write
# hero-frontend/src/deployment.ts with every resulting identifier.
#
# Prerequisites: sui CLI on PATH with a devnet env configured and an active
# address holding SUI for gas, plus jq.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DAPP_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
MOVE_DIR="${DAPP_DIR}/hero-move"
FRONTEND_SRC="${DAPP_DIR}/hero-frontend/src"

REGISTRY_ID="0xd"
PKG_MODULE="hero"   # module name inside the package

# ── 1. Require the active environment to be devnet ──────────────────────────

ACTIVE_ENV=$(sui client active-env 2>/dev/null || true)
if [ "${ACTIVE_ENV}" != "devnet" ]; then
    echo "Active env is '${ACTIVE_ENV}', expected 'devnet'." >&2
    echo "Run: sui client switch --env devnet" >&2
    exit 1
fi

ACTIVE_ADDR=$(sui client active-address)
echo "Active environment: devnet"
echo "Active address:     ${ACTIVE_ADDR}"

# ── 2. Publish ───────────────────────────────────────────────────────────────
# Devnet is ephemeral (wiped regularly), so the package system treats it like
# localnet: publications go through `test-publish`, never `publish` (which is
# reserved for the persistent testnet/mainnet deployments recorded in
# Published.toml). --build-env testnet matches where the definitive contracts
# will live.

PUBFILE="${MOVE_DIR}/.devnet-publication.json"
rm -f "${PUBFILE}"
echo "Publishing hero_forge to devnet (ephemeral test-publish)..."
PUBLISH_OUTPUT=$(sui client test-publish "${MOVE_DIR}" \
    --build-env testnet \
    --pubfile-path "${PUBFILE}" \
    --gas-budget 200000000 \
    --json)

PACKAGE_ID=$(echo "${PUBLISH_OUTPUT}" \
    | jq -r '.objectChanges[] | select(.type == "published") | .packageId')
PUBLISHER_ID=$(echo "${PUBLISH_OUTPUT}" \
    | jq -r '.objectChanges[] | select(.type == "created" and (.objectType | test("0x2::package::Publisher"))) | .objectId')

echo "Package ID:   ${PACKAGE_ID}"
echo "Publisher ID: ${PUBLISHER_ID}"

# ── 3. create_displays (Hero + 3 item Displays, one PTB) ─────────────────────

echo "Running create_displays..."
CREATE_OUTPUT=$(sui client ptb \
    --move-call "${PACKAGE_ID}::${PKG_MODULE}::create_displays" \
        "@${REGISTRY_ID}" \
        "@${PUBLISHER_ID}" \
    --gas-budget 100000000 \
    --json)

# Extract each Display<T> / DisplayCap<T> by its type parameter. Anchor "Display<"
# so it doesn't also match the DisplayCap objectType.
display_id_for() {  # $1 = type name (Hero/Sword/Shield/Armor)
    echo "${CREATE_OUTPUT}" | jq -r \
        --arg t "$1" \
        '.objectChanges[] | select(.type=="created" and (.objectType | test("display_registry::Display<.*::hero::" + $t + ">"))) | .objectId'
}
cap_id_for() {
    echo "${CREATE_OUTPUT}" | jq -r \
        --arg t "$1" \
        '.objectChanges[] | select(.type=="created" and (.objectType | test("display_registry::DisplayCap<.*::hero::" + $t + ">"))) | .objectId'
}

HERO_DISPLAY_ID=$(display_id_for Hero)
HERO_CAP_ID=$(cap_id_for Hero)
SWORD_DISPLAY_ID=$(display_id_for Sword)
SWORD_CAP_ID=$(cap_id_for Sword)
SHIELD_DISPLAY_ID=$(display_id_for Shield)
SHIELD_CAP_ID=$(cap_id_for Shield)
ARMOR_DISPLAY_ID=$(display_id_for Armor)
ARMOR_CAP_ID=$(cap_id_for Armor)

echo "Hero Display:   ${HERO_DISPLAY_ID}"
echo "Sword Display:  ${SWORD_DISPLAY_ID}"
echo "Shield Display: ${SHIELD_DISPLAY_ID}"
echo "Armor Display:  ${ARMOR_DISPLAY_ID}"

# ── 4. Write deployment.ts ───────────────────────────────────────────────────

mkdir -p "${FRONTEND_SRC}"
cat > "${FRONTEND_SRC}/deployment.ts" <<EOF
// Auto-generated by hero-scripts/publish-devnet.sh — do not edit by hand.
export const NETWORK = "devnet";
export const PACKAGE_ID = "${PACKAGE_ID}";
export const PUBLISHER_ID = "${PUBLISHER_ID}";
export const REGISTRY_ID = "${REGISTRY_ID}";

export const DISPLAYS = {
  hero:   { display: "${HERO_DISPLAY_ID}",   cap: "${HERO_CAP_ID}" },
  sword:  { display: "${SWORD_DISPLAY_ID}",  cap: "${SWORD_CAP_ID}" },
  shield: { display: "${SHIELD_DISPLAY_ID}", cap: "${SHIELD_CAP_ID}" },
  armor:  { display: "${ARMOR_DISPLAY_ID}",  cap: "${ARMOR_CAP_ID}" },
} as const;
EOF

echo ""
echo "deployment.ts written to ${FRONTEND_SRC}/deployment.ts"
echo "Done."
