#!/usr/bin/env bash
# publish-common.sh — shared core of the publish-<network>.sh wrappers. Expects:
#   NETWORK    target network name (matches the sui CLI env alias)
#   SCRIPT_DIR absolute path of the calling script's directory
# Publishes hero_forge with an ephemeral test-publish (the documented flow for
# localnet/devnet; `sui client publish` + Published.toml is reserved for the
# persistent testnet/mainnet deployments), runs create_displays (Hero + 3 item
# Displays in one PTB), and writes hero-frontend/src/deployment.ts.

set -euo pipefail

: "${NETWORK:?publish-common.sh must be sourced from a publish-<network>.sh wrapper}"
: "${SCRIPT_DIR:?publish-common.sh must be sourced from a publish-<network>.sh wrapper}"

DAPP_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
MOVE_DIR="${DAPP_DIR}/hero-move"
FRONTEND_SRC="${DAPP_DIR}/hero-frontend/src"

REGISTRY_ID="0xd"
PKG_MODULE="hero"   # module name inside the package

ACTIVE_ADDR=$(sui client active-address)
echo "Active environment: ${NETWORK}"
echo "Active address:     ${ACTIVE_ADDR}"

# ── Publish (ephemeral test-publish; testnet deps match the definitive target) ──

PUBFILE="${MOVE_DIR}/.${NETWORK}-publication.json"
rm -f "${PUBFILE}"
echo "Publishing hero_forge to ${NETWORK} (ephemeral test-publish)..."
PUBLISH_OUTPUT=$(sui client test-publish "${MOVE_DIR}" \
    --build-env testnet \
    --pubfile-path "${PUBFILE}" \
    --gas-budget 200000000 \
    --json)

PACKAGE_ID=$(echo "${PUBLISH_OUTPUT}" \
    | jq -r '.objectChanges[] | select(.type == "published") | .packageId')
PUBLISHER_ID=$(echo "${PUBLISH_OUTPUT}" \
    | jq -r '.objectChanges[] | select(.type == "created" and (.objectType | test("0x2::package::Publisher"))) | .objectId')

echo "Package ID:   ${PACKAGE_ID}"
echo "Publisher ID: ${PUBLISHER_ID}"

# ── create_displays (Hero + 3 item Displays, one PTB) ────────────────────────

echo "Running create_displays..."
CREATE_OUTPUT=$(sui client ptb \
    --move-call "${PACKAGE_ID}::${PKG_MODULE}::create_displays" \
        "@${REGISTRY_ID}" \
        "@${PUBLISHER_ID}" \
    --gas-budget 100000000 \
    --json)

# Extract each Display<T> / DisplayCap<T> by its type parameter. Anchor "Display<"
# so it doesn't also match the DisplayCap objectType.
display_id_for() {  # $1 = type name (Hero/Sword/Shield/Armor)
    echo "${CREATE_OUTPUT}" | jq -r \
        --arg t "$1" \
        '.objectChanges[] | select(.type=="created" and (.objectType | test("display_registry::Display<.*::hero::" + $t + ">"))) | .objectId'
}
cap_id_for() {
    echo "${CREATE_OUTPUT}" | jq -r \
        --arg t "$1" \
        '.objectChanges[] | select(.type=="created" and (.objectType | test("display_registry::DisplayCap<.*::hero::" + $t + ">"))) | .objectId'
}

HERO_DISPLAY_ID=$(display_id_for Hero)
HERO_CAP_ID=$(cap_id_for Hero)
SWORD_DISPLAY_ID=$(display_id_for Sword)
SWORD_CAP_ID=$(cap_id_for Sword)
SHIELD_DISPLAY_ID=$(display_id_for Shield)
SHIELD_CAP_ID=$(cap_id_for Shield)
ARMOR_DISPLAY_ID=$(display_id_for Armor)
ARMOR_CAP_ID=$(cap_id_for Armor)

echo "Hero Display:   ${HERO_DISPLAY_ID}"
echo "Sword Display:  ${SWORD_DISPLAY_ID}"
echo "Shield Display: ${SHIELD_DISPLAY_ID}"
echo "Armor Display:  ${ARMOR_DISPLAY_ID}"

# ── Write deployment.ts ───────────────────────────────────────────────────────
# PUBLISHER_ID/REGISTRY_ID/DISPLAYS aren't read by the app today, but they are
# the canonical record of the deployment — the caps in particular are what a
# future display-editing flow needs.

mkdir -p "${FRONTEND_SRC}"
cat > "${FRONTEND_SRC}/deployment.ts" <<EOF
// Auto-generated by hero-scripts/publish-${NETWORK}.sh — do not edit by hand.
export const NETWORK = "${NETWORK}";
export const PACKAGE_ID = "${PACKAGE_ID}";
export const PUBLISHER_ID = "${PUBLISHER_ID}";
export const REGISTRY_ID = "${REGISTRY_ID}";

export const DISPLAYS = {
  hero:   { display: "${HERO_DISPLAY_ID}",   cap: "${HERO_CAP_ID}" },
  sword:  { display: "${SWORD_DISPLAY_ID}",  cap: "${SWORD_CAP_ID}" },
  shield: { display: "${SHIELD_DISPLAY_ID}", cap: "${SHIELD_CAP_ID}" },
  armor:  { display: "${ARMOR_DISPLAY_ID}",  cap: "${ARMOR_CAP_ID}" },
} as const;
EOF

echo ""
echo "deployment.ts written to ${FRONTEND_SRC}/deployment.ts"
echo "Done."
