// Local publish bridge — the one thing a browser can't do: run the Sui CLI.
// Zero-dependency Node http server. Given a user-designed schema it generates the
// bespoke `display_showcase::hero` module, builds + test-publishes it to localnet,
// creates the shared Display, transfers the DisplayCap to the connected wallet, and
// returns the live object ids. Localhost only; every identifier is validated before
// codegen, so the generated Move is structurally fixed (see schema.js).
//
// Run: node dapp/scripts/bridge.mjs   (or `pnpm bridge` / `pnpm play` from dapp/frontend)

import http from 'node:http';
import { execFileSync } from 'node:child_process';
import { writeFileSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { generateHeroMove, validateSchema } from '../frontend/src/schema.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const MOVE_DIR = join(HERE, '..', 'move');
const HERO_SRC = join(MOVE_DIR, 'sources', 'hero.move');
const PUBFILE = join(MOVE_DIR, '.localnet-publication.json');
const DEPLOYMENT_TS = join(HERE, '..', 'frontend', 'src', 'deployment.ts');

const PORT = 8787;
const REGISTRY_ID = '0xd';
// Any localhost origin (the dev server's port can vary, e.g. when 5173 is taken).
// This is a localhost-only dev tool, so reflecting any loopback origin is fine.
const ALLOW_ORIGIN = /^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/;
const ADDR_RE = /^0x[0-9a-fA-F]{1,64}$/;

/** Run a sui command, returning parsed JSON stdout. Throws { stage, error } on failure. */
function sui(args, stage) {
  try {
    const out = execFileSync('sui', args, { cwd: MOVE_DIR, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
    // sui prints build warnings before the JSON; take from the first '{'.
    const i = out.indexOf('{');
    return i >= 0 ? JSON.parse(out.slice(i)) : {};
  } catch (e) {
    const detail = [e.stdout, e.stderr].filter(Boolean).join('\n') || e.message;
    throw { stage, error: detail.slice(-4000) };
  }
}

const created = (changes, re) =>
  (changes || []).find((c) => c.type === 'created' && re.test(c.objectType || ''))?.objectId;

function publish(schema, ownerAddress) {
  // 1. validate
  const errs = validateSchema(schema);
  if (errs.length) throw { stage: 'validate', error: errs.join('; ') };
  if (!ADDR_RE.test(ownerAddress || '')) throw { stage: 'validate', error: `bad ownerAddress "${ownerAddress}"` };

  // 2. codegen → write hero.move
  writeFileSync(HERO_SRC, generateHeroMove(schema));

  // 3. build (compile gate)
  sui(['move', 'build', '--build-env', 'testnet'], 'build');

  // 4. test-publish (reset pubfile for idempotency)
  rmSync(PUBFILE, { force: true });
  const pub = sui(
    ['client', 'test-publish', MOVE_DIR, '--build-env', 'testnet', '--pubfile-path', PUBFILE, '--gas-budget', '100000000', '--json'],
    'publish',
  );
  const packageId = (pub.objectChanges || []).find((c) => c.type === 'published')?.packageId;
  const publisherId = created(pub.objectChanges, /0x2::package::Publisher/);
  if (!packageId || !publisherId) throw { stage: 'publish', error: 'could not parse packageId / publisherId' };

  // 5. create_display
  const create = sui(
    ['client', 'ptb', '--move-call', `${packageId}::hero::create_display`, `@${REGISTRY_ID}`, `@${publisherId}`, '--gas-budget', '50000000', '--json'],
    'create_display',
  );
  const displayId = created(create.objectChanges, /display_registry::Display</);
  const displayCapId = created(create.objectChanges, /display_registry::DisplayCap/);
  if (!displayId || !displayCapId) throw { stage: 'create_display', error: 'could not parse Display / DisplayCap ids' };

  // 6. transfer the cap to the connected wallet
  sui(['client', 'transfer', '--to', ownerAddress, '--object-id', displayCapId, '--gas-budget', '10000000', '--json'], 'transfer');

  // 7. write deployment.ts (for the CLI/E2E path) and return
  writeFileSync(
    DEPLOYMENT_TS,
    `// Auto-generated by the publish bridge — do not edit by hand.\n` +
      `export const PACKAGE_ID = "${packageId}";\n` +
      `export const PUBLISHER_ID = "${publisherId}";\n` +
      `export const DISPLAY_ID = "${displayId}";\n` +
      `export const DISPLAY_CAP_ID = "${displayCapId}";\n` +
      `export const REGISTRY_ID = "${REGISTRY_ID}";\n`,
  );
  return { packageId, publisherId, displayId, displayCapId, registryId: REGISTRY_ID, schema };
}

function cors(req, res) {
  const origin = req.headers.origin;
  if (origin && ALLOW_ORIGIN.test(origin)) res.setHeader('Access-Control-Allow-Origin', origin);
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
}

function send(res, code, body) {
  res.writeHead(code, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify(body));
}

const server = http.createServer((req, res) => {
  cors(req, res);
  if (req.method === 'OPTIONS') return send(res, 204, {});
  if (req.method === 'GET' && req.url === '/health') return send(res, 200, { ok: true });

  if (req.method === 'POST' && req.url === '/publish') {
    let raw = '';
    req.on('data', (c) => (raw += c));
    req.on('end', () => {
      let body;
      try { body = JSON.parse(raw || '{}'); } catch { return send(res, 400, { stage: 'parse', error: 'invalid JSON body' }); }
      try {
        console.log(`[bridge] publishing ${body.schema?.typeName} → ${body.ownerAddress}`);
        const result = publish(body.schema, body.ownerAddress);
        console.log(`[bridge] published package ${result.packageId}`);
        send(res, 200, result);
      } catch (err) {
        const { stage = 'unknown', error = String(err) } = err || {};
        console.error(`[bridge] FAILED at ${stage}: ${error}`);
        send(res, 400, { stage, error });
      }
    });
    return;
  }
  send(res, 404, { error: 'not found' });
});

server.listen(PORT, () => console.log(`[bridge] listening on http://127.0.0.1:${PORT}  (POST /publish, GET /health)`));
