#!/usr/bin/env bash
set -euo pipefail

# publish.sh — build + publish display_showcase to localnet, run create_display,
# and write frontend/src/deployment.ts with the resulting identifiers.
#
# Prerequisites: sui CLI on PATH, jq, localnet running on 127.0.0.1:9000.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
MOVE_DIR="${REPO_ROOT}/dapp/move"
FRONTEND_SRC="${REPO_ROOT}/dapp/frontend/src"

LOCALNET_RPC="http://127.0.0.1:9000"
FAUCET_URL="http://127.0.0.1:9123/gas"
REGISTRY_ID="0xd"

# ── 1. Ensure active environment is localnet ─────────────────────────────────

ACTIVE_ENV=$(sui client active-env 2>/dev/null || true)
if [ "${ACTIVE_ENV}" != "localnet" ]; then
    echo "Adding/switching to localnet environment..."
    sui client new-env --alias localnet --rpc "${LOCALNET_RPC}" 2>/dev/null || true
    sui client switch --env localnet
fi
echo "Active environment: $(sui client active-env)"

# ── 2. Fund the active address from the faucet ───────────────────────────────

ACTIVE_ADDR=$(sui client active-address)
echo "Active address: ${ACTIVE_ADDR}"
echo "Requesting funds from faucet..."
curl -s -X POST "${FAUCET_URL}" \
    -H "Content-Type: application/json" \
    -d "{\"FixedAmountRequest\":{\"recipient\":\"${ACTIVE_ADDR}\"}}" | \
    jq -r '.transferredGasObjects[0].id // "faucet responded (check balance)"'

# ── 3. Build and publish the package ─────────────────────────────────────────

# Sui 1.69 package management: publishing to localnet needs EITHER an
# [environments] table in Move.toml (which pins a chain id — but
# --force-regenesis changes the localnet chain id on every restart) OR the
# ephemeral `test-publish` command. For a localnet teaching dapp we use
# test-publish. `--build-env testnet` selects the published framework to
# compile against (it matches the framework bundled in the local sui binary,
# including sui::display_registry); the package itself is published to the
# active localnet.
# test-publish records the publication (and ephemeral dependency addresses) in
# this pubfile and refuses to publish again while the entry exists. We reset it
# each run so publish.sh is idempotent — safe to re-run after a localnet
# --force-regenesis without a "package already published" error.
PUBFILE="${MOVE_DIR}/.localnet-publication.json"
rm -f "${PUBFILE}"
echo "Publishing package to localnet (ephemeral test-publish)..."
PUBLISH_OUTPUT=$(sui client test-publish "${MOVE_DIR}" \
    --build-env testnet \
    --pubfile-path "${PUBFILE}" \
    --gas-budget 100000000 \
    --json)

PACKAGE_ID=$(echo "${PUBLISH_OUTPUT}" | \
    jq -r '.objectChanges[] | select(.type == "published") | .packageId')

echo "Package ID: ${PACKAGE_ID}"

# ── 4. Extract the Publisher object id ───────────────────────────────────────

PUBLISHER_ID=$(echo "${PUBLISH_OUTPUT}" | \
    jq -r '.objectChanges[] | select(.type == "created" and (.objectType | test("0x2::package::Publisher"))) | .objectId')

echo "Publisher ID: ${PUBLISHER_ID}"

# ── 5. Run create_display (PTB: registry 0xd + Publisher → Display + DisplayCap) ─

echo "Running create_display..."
CREATE_OUTPUT=$(sui client ptb \
    --move-call "${PACKAGE_ID}::hero::create_display" \
        "@${REGISTRY_ID}" \
        "@${PUBLISHER_ID}" \
    --gas-budget 50000000 \
    --json)

# Anchor with "Display<" so this does not also match the DisplayCap objectType
# (which contains the substring "display_registry::Display" before "Cap").
DISPLAY_ID=$(echo "${CREATE_OUTPUT}" | \
    jq -r '.objectChanges[] | select(.type == "created" and (.objectType | test("display_registry::Display<"))) | .objectId')

DISPLAY_CAP_ID=$(echo "${CREATE_OUTPUT}" | \
    jq -r '.objectChanges[] | select(.type == "created" and (.objectType | test("display_registry::DisplayCap"))) | .objectId')

echo "Display ID:     ${DISPLAY_ID}"
echo "DisplayCap ID:  ${DISPLAY_CAP_ID}"

# ── 6. Write deployment.ts ────────────────────────────────────────────────────

mkdir -p "${FRONTEND_SRC}"
cat > "${FRONTEND_SRC}/deployment.ts" <<EOF
// Auto-generated by publish.sh — do not edit by hand.
export const PACKAGE_ID = "${PACKAGE_ID}";
export const PUBLISHER_ID = "${PUBLISHER_ID}";
export const DISPLAY_ID = "${DISPLAY_ID}";
export const DISPLAY_CAP_ID = "${DISPLAY_CAP_ID}";
export const REGISTRY_ID = "${REGISTRY_ID}";
EOF

echo ""
echo "deployment.ts written to ${FRONTEND_SRC}/deployment.ts"
echo "Done."
